"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.home = 'Home';
exports.services = 'Services';
exports.about = 'About';
exports.contact = 'Contact';
exports.login_signup = 'Login/Signup';
exports.search = '';
exports.home_img_title1 = 'Kall Me !';
exports.home_img_title2 = 'For anything and everything';
exports.services_header = 'Services';
exports.aboutus_header = 'About Us';
exports.aboutus_title = 'Just A Title!';
exports.address_header = 'Address';
exports.phone = '+91-80-12345678';
exports.email = 'abc@abc.com';
exports.copyright = 'Copyright © Klubibn Pvt Ltd 2017';
exports.address_description = 'I-136, SITE-C, SURAJPUR INDL. AREA, GREATER NOIDA G.B. NAGAR Gautam Buddha Nagar UP 210308 IN';
exports.rest_api_domain = 'http://kallme.in:5000';
//# sourceMappingURL=global.js.map